### ISSUE TITLE
xinput.XISelectEvents tries to pack an EventMask list by calling EventMask.synthetic

### ISSUE THREAD

**Issue by cknave** [tych0/xcffib#68]
There's a new check in `pack_list` that tries to call `pack_type.synthetic` to pack a list.  This fails:

    File "xinput2tracker.py", line 93, in _select_motion_events
      self._conn.xinput.XISelectEvents(self._root, 1, [event_mask])
    File ".venv/lib/python3.4/site-packages/xcffib/xinput.py", line 3646, in XISelectEvents
      buf.write(xcffib.pack_list(masks, EventMask))
    File ".venv/lib/python3.4/site-packages/xcffib/__init__.py", line 764, in pack_list
      return pack_type.synthetic(*from_).pack()
    TypeError: synthetic() missing 2 required positional arguments: 'mask_len' and 'mask'

I can sidestep this behavior by doing a terrible thing:

        # HACK
        emsyn = xcffib.xinput.EventMask.synthetic
        try:
            delattr(xcffib.xinput.EventMask, 'synthetic')
            self._conn.xinput.XISelectEvents(self._root, 1, [event_mask])
            self._conn.flush()
        finally:
            xcffib.xinput.EventMask.synthetic = emsyn

But I'm not sure how to fix it for real.

**Comment by tych0** [comment]
Derp again, I think the code you're hitting is just really wrong. Can you try the above patch and see if it works?

**Comment by cknave** [comment]
Works for me!

**Comment by tych0** [comment]
Cool, thanks for the report!

**Comment by orbisvicis** [comment]
I disagree with this change. It breaks compatibility with pyxb (and previous versions) and makes code overly verbose. If it's what you want, you should document this in [README.md](https://github.com/tych0/xcffib/blob/master/README.md). This is the current [XcbPythonBinding](https://xcb.freedesktop.org/XcbPythonBinding/) approach, approximately (the rects_len field is for backwards compatibility only; not used):

```
pid = connection.generate_id()
color = (65535, 0, 0, 0)
rect = (20, 20, 500, 100)
renderextension.FillRectangles(xcffib.render.PictOp.Src, pid, color, 1, rectangle)
```

The change forces this:

```
pid = connection.generate_id()
color = (65535, 0, 0, 0)
rect = (20, 20, 500, 100)
rectangle = xcffib.xproto.RECTANGLE.synthetic(*rect)
renderextension.FillRectangles(xcffib.render.PictOp.Src, pid, color, 1, [rectangle])
```

The [commit message](https://github.com/tych0/xcffib/commit/53451b9e8f0f7db28f83da61c31a783eab2aaf1f) says "we should pack each member of a list separately, instead of trying to pack the stuff in a list into the member type". If that's the case, why not do this instead:

```
 -    elif hasattr(pack_type, "synthetic"):
 -        return pack_type.synthetic(*from_).pack()
 +    elif isinstance(item, Protobj) and hasattr(pack_type, "synthetic"):
 +        return b"".join(pack_type.synthetic(f).pack() for f in from_)
```

Which results in this:

```
pid = connection.generate_id()
color = (65535, 0, 0, 0)
rect = (20, 20, 500, 100)
renderextension.FillRectangles(xcffib.render.PictOp.Src, pid, color, 1, [rectangle])
```
