### ISSUE TITLE
`bytes.join` method can not take int-type argument

### ISSUE THREAD

**Issue by OwenChia** [tych0/xcffib#85]
Hello,

A TypeError exception just raised when I try to invoke this method:
https://github.com/tych0/xcffib/blob/master/module/__init__.py#L455
```python
def buf(self):
  return b''.join(self.list)
```

I found that `self.list` is a `list` contains `int`, but `bytes.join` can only take iterable bytes-like object as argument. I fix it like below:

```python
def buf(self):
  return bytes(self.list)
```
 Now,  It works with Python 3.
Is that a bug?

**Comment by tych0** [comment]
Can you post the full stack trace and what you're trying to do?

**Comment by OwenChia** [comment]
I'm trying to rewrite [this](https://gist.github.com/liftoff/4741790) screenshot program by hylang (a dialect of Lisp that's embedded in Python).

Here is the full stack trace:
```
Traceback (most recent call last):
  File "***/venv/bin/hy", line 11, in <module>
    load_entry_point('hy==0.12.1', 'console_scripts', 'hy')()
  File "***/venv/lib64/python3.4/site-packages/hy/cmdline.py", line 342, in hy_main
    sys.exit(cmdline_handler("hy", sys.argv))
  File "***/venv/lib64/python3.4/site-packages/hy/cmdline.py", line 330, in cmdline_handler
    return run_file(options.args[0])
  File "***/venv/lib64/python3.4/site-packages/hy/cmdline.py", line 212, in run_file
    pretty_error(import_file_to_module, "__main__", filename)
  File "***/venv/lib64/python3.4/site-packages/hy/cmdline.py", line 185, in pretty_error
    return func(*args, **kw)
  File "***/venv/lib64/python3.4/site-packages/hy/importer.py", line 79, in import_file_to_module
    eval(ast_compile(_ast, fpath, "exec"), mod.__dict__)
  File "***.hy", line 30, in <module>
    (defmain [&rest _]
  File "***.hy", line 34, in _hy_anon_fn_2
    (.save (screenshot conn)
  File "***.hy", line 21, in screenshot
    (setv image-data (.buf reply.data))
  File "***/venv/lib64/python3.4/site-packages/xcffib/__init__.py", line 455, in buf
    return b''.join(self.list)
TypeError: sequence item 0: expected a bytes-like object, int found

```
This is my code:
```clojure
(import os)

(import [PIL [Image]])
(import xcffib)
(import xcffib.xproto)


(defn screenshot [conn]
  (setv screen (.  (.get-setup conn) roots [0]))
  (setv screen-width (. screen width-in-pixels))
  (setv screen-height (. screen height-in-pixels))
  (setv output-format (. xcffib xproto ImageFormat ZPixmap))
  (setv plane-mask (- (** 2 32) 1))
  (setv reply (.reply (.GetImage conn.core
                                 output-format
                                 (. screen root)
                                 0 0
                                 screen-width
                                 screen-height
                                 plane-mask)))
  (setv image-data (.buf reply.data))
  (setv im (.convert (.frombuffer Image
                                  "RGBX"
                                  (, screen-width screen-height)
                                  image-data
                                  "raw"
                                  "BGRX")
                     "RGB")))

(defmain [&rest _]
  (setv conn (.connect xcffib (.getenv os "DISPLAY")))
  (setv path "shot.png")
  (with [fd (open path "wb")]
        (.save (screenshot conn)
               fd
               :format "png")))

```

**Comment by willstott101** [comment]
I am also trying to get a bytes response from `GetImage` in python3. In fact I used the exact same gist to find a PIL conversion.

I'd reckon this looks like a bug. However the bug is with re-packing unpacked data. Which doesn't seem necessary at all to me.

Ideally I want access the buffer **before** unpacking. Which would be ideal if someone wanted to pipe the numbers into numpy or whatever too.

I ended up doing this to skip all of the automatic unpacking:
```python
plane_mask = 2**32 - 1 # No idea what this is but it works!
cookie = self.conn.core.GetImage(xcffib.xproto.ImageFormat.ZPixmap, self.pixmap, 0, 0, self.width, self.height, plane_mask)

self.conn.flush()

cookie.reply_type = lambda x: x

# ... in the future

reply = cookie.reply()
The buf had some padding, which wasn't specified in reply.padding?
data = reply.buf[reply.offset:reply.size]

pillow = Image.frombuffer("RGBX", (self.width, self.height), data, "raw", "BGRX")
```

Is there a better way to do this? If not it would be brilliant to be able to do this using a public API.

**Comment by tych0** [comment]
Oof, I totally forgot about this, thanks for bumping the thread.

r.e. your performance issue: I think that's slightly different, but it sounds completely reasonable. I'd happily accept a patch that made something like what you're after a first class API (perhaps an extra `unpack` kwarg to each request function that defaults to True, similar to `is_checked`, but I'm open to other possibilities).

In any case, I agree that the stack trace in this issue is definitely a bug, that I need to find time to fix. Thanks for the clarifications.

**Comment by tych0** [comment]
Hi guys,

I think I've fixed this with the above (both issues). Let me know if that doesn't work for you!
